sudo: required
env:
  - DOCKER_COMPOSE_VERSION=1.22.0
branches:
  only:
    - master
    - development
    - rails52
    - digitize
# override default ruby install (e.g., bundler install ...) to avoid installing outside of container
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - ./.travis.build.image.sh
script:
  - docker-compose --version
  - docker-compose -f .travis.docker-compose.yml up --force-recreate --abort-on-container-exit --exit-code-from app --renew-anon-volumes 
after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}
