#
# docker-compose targets development only
#
version: "2"
services:
  app:
    image: jhpoelen/taxonworks:development
    volumes: # mount root directory from this machine to the container itself (live development, e.g. Rails sees changes to files without rebuilding container0
      - ./.travis.test.in.container:/app/test.sh
      - ./config/database.yml.docker.compose.example:/app/config/database.yml
    ports: 
      - "127.0.0.1:3000:3000" # local:docker
    links:
      - db
    stdin_open: true
    working_dir: /app
    command:
      - /app/test.sh
  db:
    image: mdillon/postgis:10
    ports: 
      - "0.0.0.0:15432:5432"
