sudo: required
branches:
  only:
    - master
    - development
    - rails52
    - digitize
# override default ruby install (e.g., bundler install ...) to avoid installing outside of container
install:
  - ./.travis.build.image.sh
script:
  - docker-compose -f .travis.docker-compose.yml up --force-recreate --abort-on-container-exit --exit-code-from app --renew-anon-volumes 
after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}
