sudo: required
env:
  - DOCKER_COMPOSE_VERSION=1.22.0
branches:
  only:
    - master
    - development
    - rails52
    - digitize
# override default ruby install (e.g., bundler install ...) to avoid installing outside of container
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker pull ${TRAVIS_REPO_SLUG}:base || true # attempt to retrieve cached images
  - docker pull ${TRAVIS_REPO_SLUG}:base-test || true  # attempt to retrieve cached images
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --rm=false -f Dockerfile.base . --tag ${TRAVIS_REPO_SLUG}:base # keep intermediate images
  - docker push ${TRAVIS_REPO_SLUG}:base
  - echo -e "FROM ${TRAVIS_REPO_SLUG}:base\nRUN apt -y install xvfb firefox" > Dockerfile.base-test.tmp
  - docker build --rm=false -f Dockerfile.base-test.tmp . --tag ${TRAVIS_REPO_SLUG}:base-test # keep intermediate images
  - docker push ${TRAVIS_REPO_SLUG}:base-test
  - echo -e "FROM ${TRAVIS_REPO_SLUG}:base\nCMD [\"/sbin/my_init\"]" > Dockerfile.tmp

  - docker build -f Dockerfile.tmp . --tag ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}
script:
  - docker-compose --version
  - docker-compose -f .travis.docker-compose.yml up --force-recreate --abort-on-container-exit --exit-code-from app --renew-anon-volumes 
after_success:
  - docker images
  - docker push ${TRAVIS_REPO_SLUG}:${TRAVIS_BRANCH}
