#
# targets testing only
#
version: "2.1"
services:
  app:
    image: jhpoelen/taxonworks:base
    volumes:
      - ./.travis.test.in.container.sh:/app/test.sh
      - ./spec:/app/spec
      - ./config/database.yml.docker.compose.example:/app/config/database.yml
      - ./config/secrets.yml.example:/app/config/secrets.yml
    ports: 
      - "127.0.0.1:3000:3000" # local:docker
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    working_dir: /app
    command:
      - /app/test.sh
  db:
    image: mdillon/postgis:10
    expose:
     - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      retries: 3
