language: ruby 
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
    - $TRAVIS_BUILD_DIR/public/packs-test
    - /home/travis/.rvm/ 
dist: trusty
# sudo: required
rvm:
  - 2.5.1
bundler_args: --without development production
branches:
  only:
    - master
    - development
    - rails52
    - digitize
addons:
  postgresql: "10"
  firefox: "latest"
  apt:
    update: true 
    packages:
      - libgeos-dev
      - libproj-dev
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-10
      - postgresql-client-10
      - postgresql-contrib-10
env:
  global:
    - PGPORT=5433
services:
  - postgresql
before_install:
  - .travis.build.image.sh
script:
  - .travis.test.in.container.sh
after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${TRAVIS_REPO_SLUG}-dev:latest
  - docker push ${TRAVIS_REPO_SLUG}:latest
#notifications:
#  email:
#    recipients:
#      - diapriid@gmail.com
#    on_failure: change
