FROM jhpoelen/taxonworks-base-dev
MAINTAINER Matt Yoder
ENV LAST_FULL_REBUILD 2018-10-05

RUN gem install bundler && \
    bundle config --global path "$GEM_HOME" && \
    bundle config --global bin "$GEM_HOME/bin" && \
    mkdir /app

WORKDIR /app
COPY Gemfile /app
COPY Gemfile.lock /app
RUN bundle install

CMD ["exe/docker_compose_start.sh"]

