# image based on https://github.com/jhpoelen/taxonworks-base
FROM jhpoelen/taxonworks-base
MAINTAINER Matt Yoder
ENV LAST_FULL_REBUILD 2018-05-10

ADD config/docker/nginx/gzip_max.conf /etc/nginx/conf.d/gzip_max.conf

ADD package.json /app/
ADD package-lock.json /app/
ADD Gemfile /app/
ADD Gemfile.lock /app/

WORKDIR /app

RUN bundle install --without=development test
RUN npm install 
